# Generated by Django 3.1.4 on 2020-12-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.IntegerField(max_length=12)),
                ('desc', models.TextField()),
                ('city', models.CharField(max_length=122)),
                ('date', models.DateField()),
            ],
        ),
    ]
