# Generated by Django 3.1.4 on 2021-01-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201219_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
